### ISSUE TITLE
JSON overflows out of reCAPTCHA meta-box

### ISSUE THREAD

**Issue by takayukister** [takayukister/flamingo#1]
The reCAPTCHA meta-box, introduced in Flamingo 2.0, has a field for JSON-encoded response from reCAPTCHA API. When the value of the field is long and the screen width of browser is short, the content overflows out of the meta-box.

<img width="962" alt="screenshot of the issue" src="https://user-images.githubusercontent.com/4035394/59145128-aeec1100-8a1a-11e9-9e66-c8bc43b15485.png" />

There can be two approaches to address this issue. 1) Modify with CSS, 2) Insert whitespaces in appropriate places to prompt line feeds. I prefer the second approach.

You can insert whitespaces into JSON by giving the JSON_PRETTY_PRINT constant as the second parameter ("options") of [json_encode()](https://www.php.net/manual/en/function.json-encode.php). This requires PHP 5.4.0+, so we need to change the "Requires at least" version to WordPress 5.2 (because minimum PHP supported is 5.6.20) or specify the "Requires PHP" header in the readme.txt file.

I feel we can/should raise the "Requires at least" to 5.2 in the next release.

**Comment by itpixelz** [comment]
I have used `JSON_PRETTY_PRINT` as the second parameter of ` json_encode()` and it is perfect as expected for output. Due to spaces in JSON code, it is letting it break the lines without breaking the content of JSON.

`json_encode( $value, JSON_PRETTY_PRINT )`

<img width="624" alt="Screenshot 2019-06-23 at 1 23 13 AM" src="https://user-images.githubusercontent.com/3692934/59968608-a97fe200-9555-11e9-8b43-acb9bdc4477d.png">

And according to [PHP.net](https://www.php.net/manual/en/json.constants.php) it is available as of PHP 5.3.0, let's add require header tag in readme.txt at-least 5.3.

**Comment by takayukister** [comment]
Okay, let's set the "Requires PHP" header.

...but it's PHP 5.4.0, isn't it?

> JSON_PRETTY_PRINT (integer)
>    Use whitespace in returned data to format it. Available as of PHP 5.4.0.

**Comment by itpixelz** [comment]
> Okay, let's set the "Requires PHP" header.
> 
> ...but it's PHP 5.4.0, isn't it?

Yes you are right, it is 5.4.0 version

**Comment by itpixelz** [comment]
This issue has been fixed and pushed the commit.

**Comment by takayukister** [comment]
The "Requires at least" header indicates the minimum required version of WordPress, not PHP. For PHP versions you can instead use the "Requires PHP" header as explained in this plugin handbook topic.

https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

In this case, you should set

`Requires PHP: 5.4.0`

or

`Requires at least: 5.2`

since WordPress 5.2 sets its minimum required PHP version to 5.6.20.

**Comment by itpixelz** [comment]
Yes you are right, I have now used the following and pushed the update.

`Requires at least: 5.2`
