### ISSUE TITLE
Remove Inbound Messages along with Akismet's auto spam comment deletion

### ISSUE THREAD

**Issue by takayukister** [takayukister/flamingo#2]
https://wordpress.org/support/topic/spam-cleanup-for-flamingo-message-storage

Stephane suggested using the akismet_scheduled_delete action hook, but we may consider another approach, such as introducing our own scheduled event and running the job in it.

**Comment by itpixelz** [comment]
Right, as per Stephane's suggestions, we have the option to leverage the akismet_scheduled_delete action hook but I agree with your approach to keeping it our own scheduler. 

For this, we can keep spam messages for default 30 days in spam and after that, it will be deleted automatically and if a user would like to change 30 days to something else, like more or fewer days, there can be an option in the settings page for this change.

As Gmail and other email clients keep spam messages up to 30 days and after that, it automatically moves to the trash and then after 30 days of the trash, it is permanently deleted.

What are your thoughts on this?

**Comment by takayukister** [comment]
> As Gmail and other email clients keep spam messages up to 30 days and after that, it automatically moves to the trash and then after 30 days of the trash, it is permanently deleted.

Nice.

(spam) -> 30 days -> (trash) -> 30 days -> (delete permanently)

I think this is the most natural and the WordPress core handles posts and comments in the same way.

As for the (trash) -> (delete) part, we can use [wp_scheduled_delete()](https://developer.wordpress.org/reference/functions/wp_scheduled_delete/). WordPress runs this function daily, and it deletes posts in the _trash_ post_status regardless of its post_type.

So, what we need to implement is the (spam) -> (trash) part.

**Comment by itpixelz** [comment]
Perfect, so I am following this then 

> (spam) -> 30 days -> (trash) -> 30 days -> (delete permanently)
> So, what we need to implement is the (spam) -> (trash) part.

**Comment by itpixelz** [comment]
I have added functionality to trash spam posts automatically after 30 days of spam post creation via a daily cron job schedule.

Here is related [commit](https://github.com/takayukister/flamingo/commit/aea703f25ab0fe31cb6357f4b92cf7857e3aa039).

Here are the notes:
1. This update will apply to only new spam messages
2. When spam message will be created, a post meta will be saved with a timestamp for later use to find if it is ready to be trashed, the time to trash is set 30 days after creation.
3. If a post is trashed via Flamingo plugin, WordPress's default behavior will handle to delete permanently trash after 30 days.

I suggest updating version to 3.0 from 2.0 as we have made major changes in our current updates. before releasing on WP.org


I have tested this cron job functionality by applying interval of cron job to a few seconds instead of 30 days.

**Comment by takayukister** [comment]
I agree with you on the idea doing a major upgrading, but note that we follow this version numbering rule:

https://make.wordpress.org/core/handbook/about/release-cycle/version-numbering/

So, the next major version should be "2.1", not "3.0", and we will give it "2.1.1" when releasing a minor update for "2.1".

**Comment by itpixelz** [comment]
Yes, I see and got it, yes, I agree with 2.1 upcoming version. Do you want me to update version in code in my relevant pull request and also have you reviewed the code of that release so I can revise is accordingly if required?

**Comment by takayukister** [comment]
Let me check other parts first. Your code is almost perfect, looks clear and is easy to read! I'm impressed. I might be adding later some more comments about subtle coding styles.

**Comment by itpixelz** [comment]
I have pushed updated code for version 2.1 #7
